export enum CONSULTATION_STATUS {
  ACTIVE = "ACTIVE",
  CANCELED = "CANCELED",
  CREATED = "CREATED",
  DONE = "DONE",
  MOVED = "MOVED",
  MOVED_NOT_CONFIRMED = "MOVED_NOT_CONFIRMED",
  NOT_CONFIRMED = "NOT_CONFIRMED",
  PAID = "PAID",
}

export enum CONSULTATION_TYPE {
  AWAY = "AWAY",
  CUSTOM = "CUSTOM",
  OFFLINE = "OFFLINE",
  ONLINE = "ONLINE",
}
